env:
  TERM: xterm-256color

window:
  padding:
    x: 2
    y: 2
  dynamic_padding: true


font:
  normal:
    family: Hack
    style: regular
  bold:
    family: Hack
    italic:
    family: Hack
  size: 14
  offset:
    y: 1
    x: 0

background_opacity: 0.85


mouse:
  hide_when_typing: true
  url:
    # URL launcher
    launcher:
      program: xdg-open
      args: []

    # URL modifiers
    # These are the modifiers that need to be held down for opening URLs when clicking
    # on them. The available modifiers are documented in the key binding section.
    modifiers: None


cursor:
  vi_mode_style: Block

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
  # Dim colors
  dim:
    black:   '#232323'
    red:     '#74423f'
    green:   '#5e6547'
    yellow:  '#8b7653'
    blue:    '#556b79'
    magenta: '#6e4962'
    cyan:    '#5c8482'
    white:   '#828282'
  vi_mode_cursor:
    text: '#000000'
    cursor: '#f1fa8c'


key_bindings:
  - { key: V, mods: Alt,         action: Paste           }
  - { key: C, mods: Alt,         action: Copy            }
  - { key: I, mods: Alt,         action: ScrollLineUp,   mode: ~Alt }
  - { key: K, mods: Alt,         action: ScrollLineDown, mode: ~Alt }
  - { key: I, mods: Alt|Control, action: ScrollPageUp,   mode: ~Alt }
  - { key: K, mods: Alt|Control, action: ScrollPageDown, mode: ~Alt }
  - { key: Space,  mods: Alt,           action: ToggleViMode            }

    # Vi mode
  - { key: I, mode: Vi, action: Up                      }
  - { key: K, mode: Vi, action: Down                    }
  - { key: J, mode: Vi, action: Left                    }
  - { key: L, mode: Vi, action: Right                   }
  - { key: J,      mods: Shift,         mode: Vi, action: WordLeft                }
  - { key: L,      mods: Shift,         mode: Vi, action: WordRight               }
  - { key: I, mods: Shift, action: ScrollHalfPageUp,   mode: Vi }
  - { key: K, mods: Shift, action: ScrollHalfPageDown, mode: Vi }

    # unbind
  - { key: L,         mods: Control,             action: ReceiveChar }

